### ISSUE TITLE
Junit import error when running 'pytest --tests-per-worker auto' in terminal (pycharm, windows)

### ISSUE THREAD

**Issue by jakeschuler1** [browsertron/pytest-parallel#102]
PS C:\Users\Jake\PycharmProjects\stress_testing_browser> pytest --tests-per-worker auto
Traceback (most recent call last):
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jake\PycharmProjects\stress_testing_browser\venv\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pytest_concurrent\plugin.py", line 5, in <module>
    from pytest_concurrent.modes import factory
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pytest_concurrent\modes\__init__.py", line 2, in <module>
    from .mproc import MultiProcessMode as mproc
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\pytest_concurrent\modes\mproc.py", line 9, in <module>
    from _pytest.junitxml import Junit
ImportError: cannot import name 'Junit' from '_pytest.junitxml' (c:\users\jake\pycharmprojects\stress_testing_browser\venv\lib\site-packages\_pytest\junitxml.py)
PS C:\Users\Jake\PycharmProjects\stress_testing_browser>

I'm running pytest-parallel-39, wondering if this is a simply fix
-I'm attempting to use pytest-parallel for its multiprocessing capabilities...If I understand correctly then this add-on will allow me to utilize all cpus to concurrently execute multiple browsers even on the same website? 

Thank you for the help, I am a new programmer and this is my first time using this site.

**Comment by jakeschuler1** [comment]
@r2dev2 Hi, it seems you updated the pytest-parallel-39 so I will tag you aswell.

**Comment by r2dev2** [comment]
I see you seem to be using `forked` on windows. Windows does not have a `fork()` function so it will not work. Also, generally, python multiprocessing is broken on Windows and should be avoided. If you are trying to utilize all cpu cores for multiple browsers, you can create multiple selenium webdriver objects and just use the threading capabilities of this project.

If you are looking for a project which makes this capability easier, I made a library called [autoparaselenium](https://github.com/r2dev2/AutoParaSelenium) (although I am sure there are probably others that do the same job) which can help you although I have not tested it on Windows yet.
