### ISSUE TITLE
Problem with "How to contribute"

### ISSUE THREAD

**Issue by SizovIgor** [browsertron/pytest-parallel#59]
What I do:

1. git clone git@github.com:browsertron/pytest-parallel.git
2. cd pytest-parallel
3. pipenv install --dev
4. pipenv run test - in this step I have next problem:

```
$ pipenv run test
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 602, in run
    core.do_run(command=command, args=args, three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 2200, in do_run
    command = ' '.join(project.scripts[command])
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 374, in scripts
    scripts[k] = shlex.split(v, posix=True)
  File "/usr/lib/python3.7/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.7/shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'
```

What should I do for fix it ?

```
$ uname -a

Linux isizov-HP-G6 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
(pytest-parallel-RgK59dpO) isizov@isizov-HP-G6:~/GIT/pytest-parallel$ pipenv run pip freeze
astroid==2.3.3
attrs==19.3.0
bleach==3.1.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
docutils==0.15.2
entrypoints==0.3
filelock==3.0.12
flake8==3.7.9
idna==2.8
importlib-metadata==1.1.0
invoke==1.3.0
isort==4.3.21
jeepney==0.4.1
keyring==19.3.0
lazy-object-proxy==1.4.3
mccabe==0.6.1
more-itertools==8.0.0
packaging==19.2
pkg-resources==0.0.0
pkginfo==1.5.0.1
pluggy==0.13.1
py==1.8.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
pyparsing==2.4.5
pytest==5.3.1
readme-renderer==24.0
requests==2.22.0
requests-toolbelt==0.9.1
SecretStorage==3.1.1
six==1.13.0
tblib==1.5.0
toml==0.10.0
tox==3.14.2
tox-pyenv==1.1.0
tox-travis==0.12
tqdm==4.40.0
twine==3.1.1
typed-ast==1.4.0
urllib3==1.25.7
virtualenv==16.7.8
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.11.2
zipp==0.6.0
```

**Comment by alesanchezr** [comment]
I have a similar error, I think it may be a syntax issue on the pipenv
