### ISSUE TITLE
Please support Python 3.9

### ISSUE THREAD

**Issue by isac322** [browsertron/pytest-parallel#89]
When I run `pytest . --workers auto` with Python 3.9, this error occur.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/_pytest/main.py", line 255, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pytest_parallel/__init__.py", line 219, in pytest_sessionstart
INTERNALERROR>     os.environ = ThreadLocalEnviron(os.environ)
INTERNALERROR>   File "/.../venv/lib/python3.9/site-packages/pytest_parallel/__init__.py", line 122, in __init__
INTERNALERROR>     env.putenv,
INTERNALERROR> AttributeError: '_Environ' object has no attribute 'putenv'
```

So I check the code, it uses `os.environ.putenv` but Python doesn't have the API. Then only have [`os.putenv`](https://docs.python.org/3/library/os.html#os.putenv).

On Python 3.8 they are exists. 
```
Python 3.8.6 (default, Dec 11 2020, 14:45:03)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> e = os.environ
>>> e.putenv
<built-in function putenv>
>>> os.putenv == e.putenv
True
```
But 3.9 does not
```
Python 3.9.0 (default, Oct  7 2020, 23:09:01)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> e = os.environ
>>> e.putenv
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: '_Environ' object has no attribute 'putenv'
```

and definition of `_Environ` is also changed.
```python3
class _Environ(MutableMapping):
    def __init__(self, data, encodekey, decodekey, encodevalue, decodevalue):
        self.encodekey = encodekey
        self.decodekey = decodekey
        self.encodevalue = encodevalue
        self.decodevalue = decodevalue
        self._data = data
```

**Comment by paddymccrudden** [comment]
I would also be interested in having this resolved. I am hesitant to move to 3.9 until we can run our tests in parallel.

**Comment by amal-khailtash** [comment]
Making these changes works for Python 3.9+, but not sure if it breaks older releases 3.8-:

```
# pytest_parallel/__init__.py

114: class ThreadLocalEnviron(os._Environ):
115:     def __init__(self, env):
116:         super().__init__(
117:             env._data,
118:             env.encodekey,
119:             env.decodekey,
120:             env.encodevalue,
121:             env.decodevalue,
122:             # env.putenv,    # <----
123:             # env.unsetenv   # <----
124:         )

142:             os.putenv(self.encodekey(key), value)

149:             os.unsetenv(self.encodekey(key))
```

**Comment by greatzt** [comment]
I have got same issue. please fix it for 3.9

**Comment by dankush** [comment]
Also have the same issue

**Comment by liuxu7411** [comment]
Also have the same issue

**Comment by liuxu7411** [comment]
希望尽快支持3.9

**Comment by Xorag** [comment]
+1 hoping to see if the proposed PR can be merged

**Comment by sanchos** [comment]
The same issue

**Comment by paddymccrudden** [comment]
Would love this to be solved. It is preventing me from moving from 3.8

**Comment by Sumedh-Kadoo** [comment]
> e solved. It is preventing me from moving from 3.8. Is this closed as it is a pytest-parall

This project is not maintained anymore.
